name: publish crate

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v1
      with:
          check-repo: ${{ github.event_name == 'push' }}
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
